// Do not edit this file!
// This file may only be edited by Engima's ASCOM Editor!
//
// <ASCOM version="1">
// <Prefix>lamp</Prefix>
// <Functions>
// <Function Name="createTaskAttack" Params="_taskName, _caller, _tasktaker, _target" Ret="false" A="true" C="false" S="false" O="false" OC="false" P="false" />
// <Function Name="createTaskTransport" Params="_taskName, _caller, _taskTaker, _target" Ret="false" A="true" C="false" S="false" O="false" OC="false" P="false" />
// <Function Name="taskUpdate" Params="_taskName, _taskState" Ret="false" A="true" C="false" S="false" O="false" OC="false" P="false" />
// </Functions>
// </ASCOM>

ASCOM_ClientID = 0;
ASCOM_CallID = 0;
ASCOM_LastCallID = 0;
ASCOM_LockCallID = 0;

"lampcreateTaskAttackEventArgs" addPublicVariableEventHandler {
    private ["_array"];

    _array = _this select 1;

    _array spawn {
        if ((_this select 0 == "A") || (_this select 0 == "C" && !isDedicated)) then {
            (_this select 1) call lampcreateTaskAttack;
        };
    };
};

lampcreateTaskAttackAll = {
    if (isNil "_this") then { _this = []; };
    lampcreateTaskAttackEventArgs = ["A", _this];
    publicVariable "lampcreateTaskAttackEventArgs";
    _this call lampcreateTaskAttack;
    lampcreateTaskAttackEventArgs = [];
};


"lampcreateTaskTransportEventArgs" addPublicVariableEventHandler {
    private ["_array"];

    _array = _this select 1;

    _array spawn {
        if ((_this select 0 == "A") || (_this select 0 == "C" && !isDedicated)) then {
            (_this select 1) call lampcreateTaskTransport;
        };
    };
};

lampcreateTaskTransportAll = {
    if (isNil "_this") then { _this = []; };
    lampcreateTaskTransportEventArgs = ["A", _this];
    publicVariable "lampcreateTaskTransportEventArgs";
    _this call lampcreateTaskTransport;
    lampcreateTaskTransportEventArgs = [];
};


"lamptaskUpdateEventArgs" addPublicVariableEventHandler {
    private ["_array"];

    _array = _this select 1;

    _array spawn {
        if ((_this select 0 == "A") || (_this select 0 == "C" && !isDedicated)) then {
            (_this select 1) call lamptaskUpdate;
        };
    };
};

lamptaskUpdateAll = {
    if (isNil "_this") then { _this = []; };
    lamptaskUpdateEventArgs = ["A", _this];
    publicVariable "lamptaskUpdateEventArgs";
    _this call lamptaskUpdate;
    lamptaskUpdateEventArgs = [];
};



if (isServer) then {
    "ASCOM_AskForClientID" addPublicVariableEventHandler {
        private ["_unit"];

        _unit = _this select 1;
        ASCOM_AskForClientID = [];
        ASCOM_LastCallID = ASCOM_LastCallID + 1;
        ASCOM_ClientIDResponse = [_unit, ASCOM_LastCallID];
        publicVariable "ASCOM_ClientIDResponse";
    };

    ASCOM_ServerInitialized = true;
    publicVariable "ASCOM_ServerInitialized";
    ASCOM_Initialized = true;
}
else {
    "ASCOM_ClientIDResponse" addPublicVariableEventHandler {
        private ["_array"];

        _array = _this select 1;
        ASCOM_ClientIDResponse = [];

        if (player == (_array select 0)) then {
            ASCOM_ClientID = _array select 1;
            ASCOM_Initialized = true;
        };
    };

    waitUntil {!isNull player};
    ASCOM_AskForClientID = player;
    publicVariable "ASCOM_AskForClientID";
};
